Includes files from benchflow/experiments-manager repo
benchflow/benchflow pull request #194
Opened 2017-04-18 11:27 UTC by jeppe-style

2017-04-18 17:16 UTC, VincenzoFerme commented
@igormoreno adds code checker configuration
@vincenzoferme adds DevOps support

2017-04-20 13:29 UTC, VincenzoFerme requested changes
This is just a very quick review, we should plan more in depth reviews in next iterations. I am going to open an issue about this.

2017-04-20 13:29 UTC, VincenzoFerme commented on benchflow-experiment-manager/application/src/test/java/cloud/benchflow/experimentmanager/BenchFlowExperimentManagerApplicationIT.java
> +        Response response = client.target(String.format("http://localhost:%d", RULE.getLocalPort()))
Why `localhost` is hardcoded here?

2017-04-20 13:29 UTC, VincenzoFerme commented on benchflow-experiment-manager/application/src/test/java/cloud/benchflow/experimentmanager/BenchFlowExperimentManagerApplicationIT.java
> +        Response response = client.target(String.format("http://localhost:%d", RULE.getLocalPort()))
Why `localhost` is hardcoded here?

2017-04-20 13:29 UTC, VincenzoFerme commented on benchflow-experiment-manager/application/src/test/resources/data/ParallelMultiple11/1/docker-compose.yml
> +services:
This file should hide sensible data, as for example the ip

2017-04-20 13:29 UTC, VincenzoFerme commented on benchflow-experiment-manager/application/src/test/resources/data/ParallelMultiple11/1/run.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This file should hide sensible data, as for example the ip

2017-04-20 13:29 UTC, VincenzoFerme commented on benchflow-experiment-manager/pom.xml
> +                <version>1.4.0</version>
The version goes in the `<properties>` above

2017-04-20 13:29 UTC, VincenzoFerme commented on benchflow-experiment-manager/pom.xml
> +                <version>2.4.1</version>
The version goes in the `<properties>` above

2017-04-20 13:29 UTC, VincenzoFerme commented on benchflow-experiment-manager/pom.xml
> +                <version>2.6</version>
The version goes in the `<properties>` above

2017-04-20 13:29 UTC, VincenzoFerme commented on benchflow-experiment-manager/pom.xml
> +                <version>2.20</version>
The version goes in the `<properties>` above

2017-04-20 13:29 UTC, VincenzoFerme commented on benchflow-experiment-manager/pom.xml
> +                <version>2.20</version>
The version goes in the `<properties>` above

2017-04-20 14:28 UTC, jeppe-style commented on benchflow-experiment-manager/application/src/test/java/cloud/benchflow/experimentmanager/BenchFlowExperimentManagerApplicationIT.java
> +        Response response = client.target(String.format("http://localhost:%d", RULE.getLocalPort()))
There is no way (as I could figure out) to get the IP when running integration tests. Also in the dropwizard examples it is the same.

https://github.com/dropwizard/dropwizard/blob/master/dropwizard-example/src/test/java/com/example/helloworld/IntegrationTest.java

2017-04-20 14:30 UTC, jeppe-style commented on benchflow-experiment-manager/application/src/test/java/cloud/benchflow/experimentmanager/BenchFlowExperimentManagerApplicationIT.java
> +        Response response = client.target(String.format("http://localhost:%d", RULE.getLocalPort()))
There is no way (as I could figure out) to get the IP when running integration tests so it doesn't make much sense to extract this string into a variable. 

Also in the dropwizard examples they have it hardcoded: https://github.com/dropwizard/dropwizard/blob/master/dropwizard-example/src/test/java/com/example/helloworld/IntegrationTest.java#L46

2017-04-20 14:45 UTC, jeppe-style commented
@VincenzoFerme I updated the pull-request according to your suggestions. To two suggestions I provided answers. Please check if it is OK like that.

2017-04-20 14:52 UTC, VincenzoFerme commented on benchflow-experiment-manager/application/src/test/java/cloud/benchflow/experimentmanager/BenchFlowExperimentManagerApplicationIT.java
> +        Response response = client.target(String.format("http://localhost:%d", RULE.getLocalPort()))
Add a comment in the code then, so that it is more clear why you have it hardcoded

2017-04-20 14:52 UTC, VincenzoFerme commented on benchflow-experiment-manager/application/src/test/java/cloud/benchflow/experimentmanager/BenchFlowExperimentManagerApplicationIT.java
> +        Response response = client.target(String.format("http://localhost:%d", RULE.getLocalPort()))
Add a comment in the code then, so that it is more clear why you have it hardcoded

2017-04-20 15:04 UTC, jeppe-style commented on benchflow-experiment-manager/application/src/test/java/cloud/benchflow/experimentmanager/BenchFlowExperimentManagerApplicationIT.java
> +        Response response = client.target(String.format("http://localhost:%d", RULE.getLocalPort()))
done!

2017-04-20 15:04 UTC, jeppe-style commented on benchflow-experiment-manager/application/src/test/resources/data/ParallelMultiple11/1/docker-compose.yml
> +services:
done!

2017-04-20 15:04 UTC, jeppe-style commented on benchflow-experiment-manager/application/src/test/resources/data/ParallelMultiple11/1/run.xml
> +<?xml version="1.0" encoding="UTF-8"?>
done!

2017-04-20 15:13 UTC, VincenzoFerme approved these changes

2017-04-20 15:20 UTC, merged