Feature dsl experiment generation with number of users parameter
benchflow/benchflow pull request #225
Opened 2017-04-18 16:59 UTC by jeppe-style

2017-04-18 17:18 UTC, VincenzoFerme commented
@jeppe-style fix https://www.codacy.com/app/BenchFlow/benchflow/pullRequest?prid=612662, or @igormoreno improve the settings if these warnings are ok to have. Thanks!

2017-04-18 17:22 UTC, jeppe-style commented
Yes, I have changes that will solve these issues but I thought to do it in a second pull-request, basically I will remove the Try and throw an exception instead since that is easier to handle in Java anyway.

2017-04-18 19:42 UTC, jeppe-style commented
@VincenzoFerme the code is now updates so that the checks pass and now it will be easier to use in Java.

2017-04-20 16:46 UTC, VincenzoFerme requested changes
This is just a very quick review, we should plan more in depth reviews in next iterations. An issue has been opened to schedule a complete code review (#244)

2017-04-20 16:46 UTC, VincenzoFerme commented on benchflow-dsl/pom.xml
> +            <artifactId>scala-xml_2.12</artifactId>
`2.12` can also be defined as properties, or probably can be even extracted from `<scala.xml.version>` by filtering out the last `.1`. This applies to all the cases in this, and other files.

2017-04-20 16:46 UTC, VincenzoFerme commented on benchflow-dsl/src/test/resources/tests/exploration/users/benchflow-test.yml
> +  users: 10
Why do you have the setting also here, if you define an exploration space on users?

2017-04-20 22:15 UTC, igormoreno approved these changes
- Consider using string interpolation if you need to do 
too many string concatenations. I committed a small example.

- It would be nice to try to get read of those hardcoded strings: "configuration.goal.exploration_space.workload.users.". Finding your way somehow to build them dynamically. But it looks like that's not something trivial. So I would leave it for another iteration

2017-04-21 08:07 UTC, igormoreno commented
Issue regarding hardcoded strings: #249

2017-04-21 08:09 UTC, jeppe-style commented
Thanks @igormoreno and @VincenzoFerme for your comments. I have now included them so we should be good to go.

2017-04-21 09:02 UTC, VincenzoFerme approved these changes

2017-04-21 09:04 UTC, merged