Adds Pre-Computation of One-at-a-Time Exploration Space Traversal
benchflow/benchflow pull request #371
Opened 2017-05-27 19:03 UTC by jeppe-style

Fixes issue https://github.com/benchflow/benchflow/issues/370

2017-05-30 11:14 UTC, VincenzoFerme commented
@jeppe-style Lets finalise the leftover work to improve what we discussed in this pull request.

2017-05-30 13:58 UTC, jeppe-style commented
@VincenzoFerme ok - I'll add the comments also here then from https://github.com/benchflow/benchflow/pull/369#issuecomment-304846998

2017-05-30 14:24 UTC, VincenzoFerme commented
Reference the issue that discuss how this should be done.

2017-06-01 16:51 UTC, jeppe-style commented
It is the issue already referenced.

2017-06-02 08:44 UTC, VincenzoFerme requested changes

2017-06-02 08:44 UTC, VincenzoFerme commented on benchflow-dsl/src/main/scala/cloud/benchflow/dsl/ExplorationSpace.scala
> +  type ExperimentDefinitionYamlString = String
Do you need the entire definition? Isn't it enough to have the goal definition part?

2017-06-02 08:44 UTC, VincenzoFerme commented on benchflow-dsl/src/main/scala/cloud/benchflow/dsl/ExplorationSpace.scala
> +    ("to do", "to do")
In this or another pull? If another pull, reference an issue here.

2017-06-02 08:44 UTC, VincenzoFerme commented on benchflow-dsl/src/main/scala/cloud/benchflow/dsl/ExplorationSpace.scala
> +    ("to do", "to do", -1)
In this or another pull? If another pull, reference an issue here.

2017-06-02 08:44 UTC, VincenzoFerme commented on benchflow-dsl/src/main/scala/cloud/benchflow/dsl/explorationspace/ExplorationSpaceGenerator.scala
> +  /**
Why do you need this function?

2017-06-02 08:44 UTC, VincenzoFerme commented on benchflow-dsl/src/main/scala/cloud/benchflow/dsl/explorationspace/ExplorationSpaceGenerator.scala
>      memory: Option[Map[ServiceName, List[Bytes]]],
This is actually a `resource` in the DSL. I think would be better to keep the same nesting also in the code.

2017-06-02 08:44 UTC, VincenzoFerme commented on benchflow-dsl/src/main/scala/cloud/benchflow/dsl/explorationspace/ExplorationSpaceGenerator.scala
>      memory: Option[Map[ServiceName, List[Bytes]]],
The same for other cases

2017-06-02 10:12 UTC, VincenzoFerme requested changes

2017-06-02 10:12 UTC, VincenzoFerme commented on benchflow-dsl/src/main/scala/cloud/benchflow/dsl/ExplorationSpace.scala
> +      case Some(list) => experimentBuilder.numUsers(list(experimentIndex))
What happens when you do not know the experiment index?

2017-06-02 10:12 UTC, VincenzoFerme commented on benchflow-dsl/src/main/scala/cloud/benchflow/dsl/ExplorationSpace.scala
> +   * exploraiton space.
Typo

2017-06-02 10:12 UTC, VincenzoFerme commented on benchflow-dsl/src/main/scala/cloud/benchflow/dsl/ExplorationSpace.scala
> +   * Generates and experiment bundle from the given exploration space point. Assumes the point exists in the
You should check it exists, not assume it. Even though it is you system calling this method.

2017-06-02 10:12 UTC, VincenzoFerme commented on benchflow-dsl/src/main/scala/cloud/benchflow/dsl/explorationspace/ExplorationSpaceGenerator.scala
> +  /**
With a second data structure like the following, the match can be constant in time using the columns:

```
           user:5, user:10, service_a:memory:1GB, .....
row1
row2
row3
...
```

2017-06-02 10:12 UTC, VincenzoFerme commented on benchflow-dsl/src/main/scala/cloud/benchflow/dsl/explorationspace/ExplorationSpaceGenerator.scala
> +  def getExperimentIndex(
Add comments, there I can review it

2017-06-02 10:12 UTC, VincenzoFerme commented on benchflow-dsl/src/test/scala/cloud/benchflow/dsl/ExplorationSpaceTest.scala
> +  @Test def generateExperimentBundleWithConfigurationTest(): Unit = {
Where is a test testing all the expected generated experiments?

2017-06-02 10:59 UTC, jeppe-style commented on benchflow-dsl/src/main/scala/cloud/benchflow/dsl/ExplorationSpace.scala
> +  type ExperimentDefinitionYamlString = String
I don't get the question fully

2017-06-02 11:01 UTC, jeppe-style commented on benchflow-dsl/src/main/scala/cloud/benchflow/dsl/explorationspace/ExplorationSpaceGenerator.scala
>      memory: Option[Map[ServiceName, List[Bytes]]],
I wanted remove the nesting so it is more clear and to avoid having to access another layer

2017-06-02 11:02 UTC, jeppe-style commented on benchflow-dsl/src/main/scala/cloud/benchflow/dsl/ExplorationSpace.scala
> +  type ExperimentDefinitionYamlString = String
this is a return a return type

2017-06-02 11:05 UTC, VincenzoFerme commented on benchflow-dsl/src/main/scala/cloud/benchflow/dsl/explorationspace/ExplorationSpaceGenerator.scala
>      memory: Option[Map[ServiceName, List[Bytes]]],
It is fine, but please add some comments

2017-06-02 11:06 UTC, VincenzoFerme commented on benchflow-dsl/src/main/scala/cloud/benchflow/dsl/ExplorationSpace.scala
> +      case Some(list) => experimentBuilder.numUsers(list(experimentIndex))
There is another function handling it

2017-06-02 18:21 UTC, jeppe-style commented on benchflow-dsl/src/main/scala/cloud/benchflow/dsl/ExplorationSpace.scala
> +   * Generates and experiment bundle from the given exploration space point. Assumes the point exists in the
I just saw this was an old commit. It actually returns an option, e.g., `None` if the point doesn't exist (or more than one). I will update the JavaDoc.

2017-06-02 18:26 UTC, jeppe-style commented on benchflow-dsl/src/main/scala/cloud/benchflow/dsl/explorationspace/ExplorationSpaceGenerator.scala
> +  /**
Here is an issue for reference https://github.com/benchflow/benchflow/issues/386

2017-06-02 18:46 UTC, jeppe-style commented on benchflow-dsl/src/test/scala/cloud/benchflow/dsl/ExplorationSpaceTest.scala
> +  @Test def generateExperimentBundleWithConfigurationTest(): Unit = {
it is in another file https://github.com/benchflow/benchflow/pull/371/files/7ae4fe21d3437049d02e21af0f53c94e7da611f0..402fc9aee93e331b276badfd9f39a92cdee88291#diff-173d315759c44281b5ce418acd20b7fcR74

2017-06-02 18:52 UTC, jeppe-style commented on benchflow-dsl/src/main/scala/cloud/benchflow/dsl/explorationspace/ExplorationSpaceGenerator.scala
> +  def getExperimentIndex(
comments have been added

2017-06-03 08:21 UTC, VincenzoFerme requested changes

2017-06-03 08:21 UTC, VincenzoFerme commented on benchflow-dsl/src/test/scala/cloud/benchflow/dsl/ExplorationSpaceTest.scala
> +  @Test def generateExperimentBundleWithConfigurationTest(): Unit = {
This is about an experiment bundle.

2017-06-03 08:21 UTC, VincenzoFerme commented on benchflow-dsl/src/main/scala/cloud/benchflow/dsl/ExplorationSpace.scala
> +   *         (index in exploration space) as an Option. None if point could not be found, or if multiple were found.
You need two different return types for te described cases. If multiple have been found it has to throw an error.

2017-06-03 09:05 UTC, jeppe-style commented on benchflow-dsl/src/main/scala/cloud/benchflow/dsl/ExplorationSpace.scala
> +   *         (index in exploration space) as an Option. None if point could not be found, or if multiple were found.
I use an [Option](https://www.scala-lang.org/api/current/scala/Option.html) for that. The calling class has to unwrap that and handle the two cases (`Some` or `None`).

2017-06-03 09:10 UTC, jeppe-style commented on benchflow-dsl/src/main/scala/cloud/benchflow/dsl/explorationspace/ExplorationSpaceGenerator.scala
> +  /**
Isn't it clear from the description?
It is used to create the combinations of a given dimension (each dimension is stored in a list) to produce the cartesian product.

2017-06-03 11:03 UTC, VincenzoFerme commented on benchflow-dsl/src/main/scala/cloud/benchflow/dsl/explorationspace/ExplorationSpaceGenerator.scala
> +  /**
It is not, add a comment with an example that clarify what is the input and what you actually do in this method, please.

2017-06-03 11:04 UTC, VincenzoFerme commented on benchflow-dsl/src/main/scala/cloud/benchflow/dsl/ExplorationSpace.scala
> +   *         (index in exploration space) as an Option. None if point could not be found, or if multiple were found.
@jeppe-style I understand but how do you handle the difference between 0 point and multiple points? I don’t see any difference. I think it is enough to say that this is not a valid configuration.

2017-06-03 11:04 UTC, VincenzoFerme commented on benchflow-dsl/src/main/scala/cloud/benchflow/dsl/ExplorationSpace.scala
> +   *         (index in exploration space) as an Option. None if point could not be found, or if multiple were found.
Ah, now it is clear, make it explicit in the Javadoc please.

2017-06-03 11:05 UTC, VincenzoFerme commented on benchflow-dsl/src/main/scala/cloud/benchflow/dsl/ExplorationSpace.scala
> +   *         (index in exploration space) as an Option. None if point could not be found, or if multiple were found.
The important thing to me is that in the caller you can distinguish the two cases, because you need for sure to generate different error messages.

2017-06-03 11:37 UTC, jeppe-style commented on benchflow-dsl/src/main/scala/cloud/benchflow/dsl/ExplorationSpace.scala
> +   *         (index in exploration space) as an Option. None if point could not be found, or if multiple were found.
I updated the JavaDoc to clarify when `Some` or `None` is returned.

2017-06-03 16:17 UTC, jeppe-style commented on benchflow-dsl/src/main/scala/cloud/benchflow/dsl/explorationspace/ExplorationSpaceGenerator.scala
> +  /**
The examples are already there, is this really not enough?
```
Fills a list with indices for calculating the cartesian product.
If we want to create the list [0,0,1,1,2,2] we would pass: blockSize = 2, numValues = 3, listLength = 6
If we want to create the list [0,1,2,0,1,2] we would pass: blockSize = 1, numValues = 3, listLength = 6
```

2017-06-03 18:12 UTC, VincenzoFerme approved these changes

2017-06-03 18:15 UTC, merged