Assert deployment descriptor generation
benchflow/benchflow pull request #414
Opened 2017-06-16 09:07 UTC by jeppe-style

as per title

2017-06-17 09:11 UTC, VincenzoFerme requested changes

2017-06-17 09:11 UTC, VincenzoFerme commented on benchflow-test-manager/application/src/test/java/cloud/benchflow/testmanager/scheduler/TestTaskSchedulerIT.java
> +
You should have assertion for the entire space, or better point me to the unit test where you do that.

2017-06-17 09:11 UTC, VincenzoFerme commented on benchflow-test-manager/application/src/test/resources/data/deployment/docker-compose.yml
> +version: '2'
Update with the last discussed definition

2017-06-17 09:11 UTC, VincenzoFerme commented on benchflow-test-manager/application/src/test/resources/data/exploration/one-at-a-time/users-memory-environment/benchflow-test.yml
>            memory:
Make it more realistic as discussed, then it is fine to use ranges

2017-06-17 11:10 UTC, jeppe-style commented on benchflow-test-manager/application/src/test/java/cloud/benchflow/testmanager/scheduler/TestTaskSchedulerIT.java
> +
I don't get what you mean. Here I assert that all experiments have been executed in the expected order. In the DSL there are detailed tests regarding the size of the exploration space.

2017-06-17 11:12 UTC, jeppe-style commented on benchflow-test-manager/application/src/test/resources/data/exploration/one-at-a-time/users-memory-environment/benchflow-test.yml
>            memory:
It was a mistake to test for ranges because it generates too many experiments - detailed tests are in the DSL.

2017-06-19 07:29 UTC, VincenzoFerme commented
@jeppe-style here we also have Conflicting files

2017-06-19 10:14 UTC, jeppe-style commented
@VincenzoFerme I solved the conflicts but it added a new commit....

2017-06-19 11:52 UTC, VincenzoFerme commented
@jeppe-style no problem. Fix https://github.com/benchflow/benchflow/pull/414#pullrequestreview-44696605 and then do an interactive rebase to clean up the history to get the pull request ready for merge.

2017-06-19 13:05 UTC, jeppe-style commented on benchflow-test-manager/application/src/test/resources/data/deployment/docker-compose.yml
> +version: '2'
@VincenzoFerme I just checked and that is the same as we used for the demo.

2017-06-19 13:26 UTC, jeppe-style commented
The review should be fixed. I don't know how to rebase since the conflicts were solved in the last commit.

2017-06-19 13:55 UTC, VincenzoFerme commented on benchflow-test-manager/application/src/test/resources/data/deployment/docker-compose.yml
> +version: '2'
Use the following so we keep track of the attempted improvement to use volumes that should work:

```YAML
version: '2'
services:
  camunda:
    image: 'camunda/camunda-bpm-platform:tomcat-7.5.0'
    command: bash -c "sleep 40 && /usr/local/bin/configure-and-run.sh"
    environment:
      - DB_DRIVER=com.mysql.jdbc.Driver
      - DB_PASSWORD=${BENCHFLOW_db_MYSQL_PASSWORD}
      - DB_URL=jdbc:mysql://${BENCHFLOW_db_IP}:${BENCHFLOW_db_PORT}/${BENCHFLOW_db_MYSQL_DATABASE}
      - DB_USERNAME=${BENCHFLOW_db_MYSQL_USER}
      - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom
    #The Camunda's way to disable examples (https://github.com/camunda/docker-camunda-bpm-platform#clean-distro-without-webapps-and-examples)
    volumes:
      - /home/vferme/webapps:/camunda/webapps/camunda-invoice/
      - /home/vferme/webapps:/camunda/webapps/examples/
      # - data:/camunda/webapps/camunda-invoice/:rw
      # - data:/camunda/webapps/examples/:rw
    network_mode: host
    ports:
      - 8080:8080

  db:
    image: 'mysql:5.7.17'
    environment:
      - MYSQL_DATABASE=process-engine
      - MYSQL_PASSWORD=camunda
      - MYSQL_ROOT_PASSWORD=camunda
      - MYSQL_USER=camunda
    network_mode: host
    ports:
      - 3306:3306

# volumes:
#   data:
#     driver: local
```

2017-06-19 14:10 UTC, jeppe-style commented on benchflow-test-manager/application/src/test/resources/data/deployment/docker-compose.yml
> +version: '2'
ok - I pushed the changes now

2017-06-19 15:09 UTC, VincenzoFerme approved these changes

2017-06-19 15:09 UTC, merged