Updates DSL version
benchflow/benchflow pull request #466
Opened 2017-06-25 15:08 UTC by jeppe-style

As per title. In addition:
- Adds dynamic creation of test bundles for testing. 
- Adds response message to InvalidTestBundleWebException.

2017-06-26 10:35 UTC, VincenzoFerme commented
@jeppe-style a test failed https://app.wercker.com/BenchFlow/benchflow/runs/build-benchflow-test-manager/594fd344c0556700012b4db5?step=594fd3e742d5cc00014db14f

2017-06-26 13:57 UTC, VincenzoFerme requested changes

2017-06-26 13:57 UTC, VincenzoFerme commented on benchflow-test-manager/application/src/test/resources/data/definition/exhaustive_exploration/one-at-a-time/users-memory-environment/benchflow-test.yml
> +      camunda: grid
Use anonymous server names. This applies to all the test files.

2017-06-30 13:01 UTC, jeppe-style commented on benchflow-test-manager/application/src/test/resources/data/definition/exhaustive_exploration/one-at-a-time/users-memory-environment/benchflow-test.yml
> +      camunda: grid
changed

2017-07-06 12:22 UTC, VincenzoFerme commented
@jeppe-style see #402 (comment)

2017-07-10 07:11 UTC, merged