Adds links response objects
benchflow/benchflow pull request #469
Opened 2017-06-30 22:50 UTC by jeppe-style

as per title

fixes https://github.com/benchflow/benchflow/issues/445

- `collectedData: URL` misses full path (needs hash, not sure of what)

depends on PR https://github.com/benchflow/benchflow/pull/468

2017-07-10 09:47 UTC, VincenzoFerme requested changes
See https://github.com/benchflow/benchflow/issues/445#issuecomment-314056238.

Moreover, do not save URLs to the database, they need to be generated on the fly and they should be positioned in a dedicated section in the response, not mixed with other fields, see: https://github.com/benchflow/benchflow/issues/128#issuecomment-313679357. The fields should only contain human readable data, so if you want to extend some of them with actual content feel free to do so.

2017-07-19 20:54 UTC, jeppe-style commented
@VincenzoFerme I think your comments can be added to an issue. Right now it works and serves the purpose of the demo and use cases.

2017-07-20 10:11 UTC, VincenzoFerme approved these changes

2017-07-20 10:11 UTC, VincenzoFerme commented
What is left in this PR, is documented in https://github.com/benchflow/benchflow/issues/445#issuecomment-316657447 for future improvement.

2017-07-20 10:14 UTC, merged