Updates DSL version
benchflow/benchflow pull request #471
Opened 2017-07-01 13:32 UTC by jeppe-style

as per title

depends on PR https://github.com/benchflow/benchflow/pull/470

2017-07-10 10:43 UTC, VincenzoFerme requested changes

2017-07-10 10:43 UTC, VincenzoFerme commented on benchflow-experiment-manager/application/src/main/java/cloud/benchflow/experimentmanager/tasks/start/StartTask.java
> +      int numTrials =
What happens if this is not defined?

2017-07-12 11:33 UTC, jeppe-style commented on benchflow-experiment-manager/application/src/main/java/cloud/benchflow/experimentmanager/tasks/start/StartTask.java
> +      int numTrials =
It has to be defined otherwise the DSL library will throw an exception

2017-08-03 09:04 UTC, VincenzoFerme approved these changes

2017-08-03 09:06 UTC, merged