Updates handling of Faban results
benchflow/benchflow pull request #472
Opened 2017-07-01 21:53 UTC by jeppe-style

as per title

fixes https://github.com/benchflow/benchflow/issues/440

depends on PR https://github.com/benchflow/benchflow/pull/471

2017-07-10 11:27 UTC, VincenzoFerme requested changes

2017-07-10 11:27 UTC, VincenzoFerme commented on benchflow-experiment-manager/application/src/main/java/cloud/benchflow/experimentmanager/tasks/running/CheckTrialResultTask.java
> +      } else {
If `failureStatus = FailureStatus.EXECUTION;` here you set `TrialExecutionStatus.SUCCESS`.

2017-07-10 11:27 UTC, VincenzoFerme commented on benchflow-experiment-manager/application/src/main/java/cloud/benchflow/experimentmanager/tasks/running/CheckTrialResultTask.java
> +          return TrialExecutionStatus.SUCCESS;
Don't return in a `switch` block

2017-07-10 11:27 UTC, VincenzoFerme commented on benchflow-experiment-manager/application/src/main/java/cloud/benchflow/experimentmanager/tasks/running/CheckTrialResultTask.java
> +        case RANDOM_FAILURE:
Why don't you have an intermediate status also for this cases, so that you can decide all out of the switch statement?

2017-07-10 11:27 UTC, VincenzoFerme commented on benchflow-experiment-manager/application/src/main/java/cloud/benchflow/experimentmanager/tasks/running/CheckTrialResultTask.java
> +      if (failureStatus == null) {
I think this anyway should happen in the controller, because you have to drive the control flow according to the status you get

2017-07-10 11:27 UTC, VincenzoFerme commented on benchflow-experiment-manager/application/src/main/java/cloud/benchflow/experimentmanager/scheduler/ExperimentTaskScheduler.java
>        // TODO - change this when faban interaction changes to non-polling
Change how? Reference to an issue

2017-07-10 11:27 UTC, VincenzoFerme commented on benchflow-experiment-manager/application/src/main/java/cloud/benchflow/experimentmanager/scheduler/ExperimentTaskScheduler.java
> +    } else {
`KILLED, KILLING` look more like `ABORT` to me.

2017-07-19 20:59 UTC, jeppe-style commented on benchflow-experiment-manager/application/src/main/java/cloud/benchflow/experimentmanager/tasks/running/CheckTrialResultTask.java
> +        case RANDOM_FAILURE:
because the switch is on TrialStatus

2017-07-19 21:00 UTC, jeppe-style commented on benchflow-experiment-manager/application/src/main/java/cloud/benchflow/experimentmanager/tasks/running/CheckTrialResultTask.java
> +      if (failureStatus == null) {
the controller decides what to do next - here we just provide the values in order to make the decision

2017-07-19 21:05 UTC, jeppe-style commented on benchflow-experiment-manager/application/src/main/java/cloud/benchflow/experimentmanager/scheduler/ExperimentTaskScheduler.java
>        // TODO - change this when faban interaction changes to non-polling
I'll do that when I go through all the TODO's in the end

2017-07-19 21:06 UTC, jeppe-style commented on benchflow-experiment-manager/application/src/main/java/cloud/benchflow/experimentmanager/tasks/running/CheckTrialResultTask.java
> +          return TrialExecutionStatus.SUCCESS;
Why? There is no code style warning and I don't need to execute anything further.

2017-07-19 21:14 UTC, jeppe-style commented on benchflow-experiment-manager/application/src/main/java/cloud/benchflow/experimentmanager/tasks/running/CheckTrialResultTask.java
> +        case RANDOM_FAILURE:
The switch statement is complete. For a trial there are only three possible status values: SUCCESS, FAILED or RANDOM_FAILURE.

2017-07-19 21:15 UTC, jeppe-style commented on benchflow-experiment-manager/application/src/main/java/cloud/benchflow/experimentmanager/tasks/running/CheckTrialResultTask.java
> +      if (failureStatus == null) {
I drive it with the `TrialExecutionStatus` that is returned

2017-07-19 21:17 UTC, jeppe-style commented on benchflow-experiment-manager/application/src/main/java/cloud/benchflow/experimentmanager/tasks/running/CheckTrialResultTask.java
> +      } else {
This is because the experiment failed (FailureStatus) but the trial executions is successful since there is no re-tries anymore.

2017-07-19 21:19 UTC, jeppe-style commented on benchflow-experiment-manager/application/src/main/java/cloud/benchflow/experimentmanager/scheduler/ExperimentTaskScheduler.java
> +    } else {
Not sure what you mean. There is no `ABORT` for the trial.

2017-08-03 11:22 UTC, VincenzoFerme commented on benchflow-experiment-manager/application/src/main/java/cloud/benchflow/experimentmanager/tasks/running/CheckTrialResultTask.java
> +      } else {
All right, this is the ExecutionStatus (either complete the execution or need to be re-executed), then the actual Result returned as Faban Status is handled in a different way.

2017-08-03 11:28 UTC, VincenzoFerme commented on benchflow-experiment-manager/application/src/main/java/cloud/benchflow/experimentmanager/scheduler/ExperimentTaskScheduler.java
>        // TODO - change this when faban interaction changes to non-polling
Ok, the activity is tracked in the following issue: https://github.com/benchflow/benchflow/issues/57

2017-08-03 11:35 UTC, VincenzoFerme commented on benchflow-experiment-manager/application/src/main/java/cloud/benchflow/experimentmanager/scheduler/ExperimentTaskScheduler.java
> +    } else {
Ok for now, see https://github.com/benchflow/benchflow/issues/516

2017-08-03 11:42 UTC, VincenzoFerme submitted a review, later dismissed

2017-08-03 11:45 UTC, VincenzoFerme approved these changes

2017-08-03 11:58 UTC, merged