Adds exploration point api
benchflow/benchflow pull request #478
Opened 2017-07-05 10:34 UTC by jeppe-style

as per title

fixes https://github.com/benchflow/benchflow/issues/418

depends on PR

2017-07-05 18:52 UTC, jeppe-style commented
if there is no exploration space there should not be any reference to the exploration space

2017-07-10 17:41 UTC, VincenzoFerme requested changes

2017-07-10 17:41 UTC, VincenzoFerme commented on benchflow-test-manager/application/src/main/java/cloud/benchflow/testmanager/models/explorationspace/MongoCompatibleExplorationSpace.java
> +    if (index >= size || index < 0) {
This should be an error, not an empty response.

2017-07-10 17:41 UTC, VincenzoFerme commented on benchflow-test-manager/application/src/main/java/cloud/benchflow/testmanager/models/explorationspace/MongoCompatibleExplorationSpace.java
> +    usersDimension
Why is the following not exposed as part of the APIs of the DSL?

2017-07-10 17:41 UTC, VincenzoFerme commented on benchflow-test-manager/application/src/main/java/cloud/benchflow/testmanager/resources/BenchFlowTestResource.java
> +        if (explorationSpace == null || explorationSpace.getSize() == 0) {
The field should not be visualised in the response in this case

2017-07-19 22:19 UTC, jeppe-style commented on benchflow-test-manager/application/src/main/java/cloud/benchflow/testmanager/models/explorationspace/MongoCompatibleExplorationSpace.java
> +    if (index >= size || index < 0) {
I don't see how this changes the functionality

2017-07-19 22:21 UTC, jeppe-style commented on benchflow-test-manager/application/src/main/java/cloud/benchflow/testmanager/models/explorationspace/MongoCompatibleExplorationSpace.java
> +    usersDimension
I don't get it. Why should the response be part of the DSL?

2017-07-19 22:24 UTC, jeppe-style commented on benchflow-test-manager/application/src/main/java/cloud/benchflow/testmanager/resources/BenchFlowTestResource.java
> +        if (explorationSpace == null || explorationSpace.getSize() == 0) {
I suggest to move this into an issue since it is not important for the use cases.

2017-08-10 07:39 UTC, VincenzoFerme commented on benchflow-test-manager/application/src/main/java/cloud/benchflow/testmanager/models/explorationspace/MongoCompatibleExplorationSpace.java
> +    if (index >= size || index < 0) {
It becomes a proper API, with proper response codes.

2017-08-10 07:40 UTC, VincenzoFerme commented on benchflow-test-manager/application/src/main/java/cloud/benchflow/testmanager/models/explorationspace/MongoCompatibleExplorationSpace.java
> +    if (index >= size || index < 0) {
Postponed in https://github.com/benchflow/benchflow/issues/494

2017-08-10 07:44 UTC, VincenzoFerme approved these changes

2017-08-10 07:44 UTC, VincenzoFerme commented on benchflow-test-manager/application/src/main/java/cloud/benchflow/testmanager/models/explorationspace/MongoCompatibleExplorationSpace.java
> +    usersDimension
My fault

2017-08-10 07:44 UTC, VincenzoFerme commented on benchflow-test-manager/application/src/main/java/cloud/benchflow/testmanager/resources/BenchFlowTestResource.java
> +        if (explorationSpace == null || explorationSpace.getSize() == 0) {
Postponed in https://github.com/benchflow/benchflow/issues/494

2017-08-10 07:53 UTC, merged